---

- name: Verify ACI Config
  hosts: all
  connection: local
  collections:
    - cisco.nae
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: 10.66.176.111
        username: admin
        password: C@ndidadmin1234  
    validate_certs: False
  
  tasks:
    - name: Get PCV Result
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "STLD_FAB1"
        name: PCV_Demo_OK
        state: query
        verify: True
