---

- name: Verify ACI Config
  hosts: all
  collections:
  - cisco.nae
  connection: local
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: 10.67.185.100
        port: 8448  
        username: admin
        password: C@ndidadmin1234  
    validate_certs: False
  
  tasks:
    - name: Create a pre-change analysis
      nae_prechange:
        <<: *nae_login
        ag_name: PCV_DataSet
        file: config.json
        name: PCV_Demo
        state: present
        verify: True
    - name: Get PCV Result
      nae_prechange:
        <<: *nae_login
        ag_name: PCV_DataSet
        name: PCV_Demo
        state: query
        verify: True
