---

- name: Verify ACI Config
  hosts: all
  connection: local
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: 10.67.185.100
        port: 8448  
        username: admin
        password: C@ndidadmin1234  
    validate_certs: False
  
  tasks:

    - name: Create a pre-change analysis and wait for result
      nae_prechange:
         <<: *nae_login
         ag_name: FAB2
         file: dump.json
         name: PCD
         state: query
