---

- name: Verify ACI Config
  hosts: all
  connection: local
  collections:
    - cisco.nae
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: 10.67.185.6
        username: admin
        password: C@ndidadmin1234  
    validate_certs: False
  
  tasks:
    - name: Create a pre-change analysis
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "Change Management"
        name: PCV_Demo
        state: present
        verify: True
        file: config.json
    - name: Get PCV Result
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "Change Management"
        name: PCV_Demo
        state: query
        verify: True
