---

- name: playbook for testing anp's and epg's
  hosts: all
  collections:
   - cisco.aci
  connection: local
  gather_facts: yes
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: ansible
      private_key: 'ansible.key'
      use_proxy: 'no'
      validate_certs: '{{ validate_certs }}'
      port: '{{ port }}'
    tenantName: 'nae-prod'
    vrfName: 'prod-vrf'
    vmmDomain: 'ACI'

  tasks:
    - name: ensure tenant exists
      aci_tenant:
        <<: *aci_login
        name: '{{ tenantName }}'
        descr: 'CDCI'
        state: present
        output_path: 'config.json'

    - name: ensure context for tenant exists
      aci_vrf:
        <<: *aci_login
        tenant: '{{ tenantName }}'
        name: '{{ vrfName }}'
        state: present
        output_path: 'config.json'

    - name: ensure bridge domain 1 exists
      aci_bd:
        <<: *aci_login
        name: BD1
        vrf: '{{ vrfName }}'
        tenant: '{{ tenantName }}'
        state: present
        output_path: 'config.json'

    - name: add subnet to BD
      aci_bd_subnet:
        <<: *aci_login
        tenant: '{{ tenantName }}'
        bd: BD1
        subnet_name: BD1
        gateway: 10.66.0.1
        mask: 24
        state: present
        output_path: 'config.json'